name: Publish Maven package to GitHub Packages
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Get Git Tag
        run: |
          TAG_VERSION=$( echo ${{github.ref_name}} | sed 's/[^0-9.]//g' )
          echo "TAG_VERSION=${TAG_VERSION}" >> $GITHUB_ENV
      - name: Get Maven Version
        run: |
          MAVEN_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "MAVEN_VERSION=${MAVEN_VERSION}" >> $GITHUB_ENV
      - name: Check Tag and Version Match
        run: |
          if [ "${{ env.TAG_VERSION }}" != "${{ env.MAVEN_VERSION }}" ]; then
            echo "Git tag (${{ env.TAG_VERSION }}) does not match POM version (${{ env.MAVEN_VERSION }})"
            exit 1
          fi
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get Maven Properties
        run: |
          ARTIFACT_ID=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout | tail -n 1 | tr -d '\n')
          GROUP_ID=$(mvn help:evaluate -Dexpression=project.groupId -q -DforceStdout | tail -n 1 | tr -d '\n')
          MAVEN_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout | tail -n 1 | tr -d '\n')
          echo "ARTIFACT_ID=${ARTIFACT_ID}" >> $GITHUB_ENV
          echo "GROUP_ID=${GROUP_ID}" >> $GITHUB_ENV
          echo "MAVEN_VERSION=${MAVEN_VERSION}" >> $GITHUB_ENV
      - name: Publish package under 1x postfix
        run: |
          mvn deploy:deploy-file \
            -DgroupId=${{ env.GROUP_ID }} \
            -DartifactId=${{ env.ARTIFACT_ID }}-1x \
            -Dversion=${{ env.MAVEN_VERSION }} \
            -Dpackaging=jar \
            -Dfile=target/${{ env.ARTIFACT_ID }}-${{ env.MAVEN_VERSION }}.jar \
            -DrepositoryId=github \
            -Durl=https://maven.pkg.github.com/${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}