name: Publish Maven package to GitHub Packages
on:
  push:
    branches: # Execute on "main" branch and product branches, avoid others
      - 'main' # Main branch
      - '*.*' # Product branches (e.g., 0.7, 0.x, 1.x, ...)
  pull_request:
    branches:
      - 'main' # Main branch
      - '*.*' # Product branches (e.g., 0.7, 0.x, 1.x, ...)
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Execute tests with Maven
        run: mvn test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}